### ISSUE TITLE
BUG:  Mobile/bootstrap is INOP

### ISSUE THREAD

**Issue by seanvree** [seanvree/homepage#2]
mobile view is all screwed up.

**Comment by haltdev** [comment]
Fixed in dev.

**Comment by seanvree** [comment]
Still needs a bit of work, but huge improvement.  Leaving it open. 

Committed to MASTER

https://github.com/seanvree/homepage/commit/5e3fe008b7e8f78e7552c0968274feccb9c9220b

**Comment by seanvree** [comment]
Fixed. Closed

https://github.com/seanvree/homepage/commit/0609621d16628277b37097918f4f5f74a3134763
