### ISSUE TITLE
Feature: Bookmarks

### ISSUE THREAD

**Issue by kunago** [seanvree/homepage#32]
Have you thought about integrating a support for bookmarks?

**Comment by seanvree** [comment]
@kunago  I have. You have an example?

**Comment by seanvree** [comment]
Hey @kunago  not sure if you are still interested, but you can change/add bookmarks in the file `/js/tilde.js`

https://github.com/seanvree/homepage#live-search-usage

https://github.com/seanvree/homepage/blob/master/js/tilde.js
